export const CALCULATE_FIBONACCI_REQUEST = "CALCULATE_FIBONACCI_REQUEST";
export const CALCULATE_FIBONACCI_FAILURE = "CALCULATE_FIBONACCI_FAILURE";
export const CALCULATE_FIBONACCI_SUCCESS = "CALCULATE_FIBONACCI_SUCCESS";
export const CALCULATE_FIBONACCI_CLEAR = "CALCULATE_FIBONACCI_CLEAR";
